<a href="https://colab.research.google.com/github/sardarabdulsammad/DeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
print(torch.__version__)

2.4.0+cu121


## tensors Introduction

### Creating Tensors

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
matrix.shape

torch.Size([2, 2])

##Random Tensors

Start with Random Number -> look at data -> update random numbers -> look at data -> update random numbers

In [8]:
#create random tensor

random_tensor = torch.rand(10,10,10)

In [9]:
random_tensor

tensor([[[6.0006e-02, 3.4161e-02, 1.3648e-01, 4.1250e-01, 4.8693e-01,
          4.1208e-01, 2.9405e-01, 1.4325e-02, 8.2788e-01, 7.4172e-01],
         [6.4281e-01, 9.3081e-01, 7.5361e-01, 1.0568e-01, 2.8505e-01,
          9.1746e-01, 1.0030e-01, 1.1674e-01, 6.1520e-01, 2.5918e-01],
         [9.1394e-01, 1.7857e-01, 3.8932e-01, 5.4318e-02, 9.1215e-01,
          3.6771e-01, 3.9628e-01, 4.0200e-01, 5.9212e-01, 7.4651e-01],
         [2.7257e-02, 6.1365e-01, 5.3721e-01, 2.5987e-01, 4.6494e-01,
          9.8740e-01, 2.0053e-01, 7.3684e-02, 5.6788e-01, 7.8585e-01],
         [9.3862e-02, 3.3361e-01, 2.2606e-01, 5.6637e-01, 5.7812e-02,
          7.9914e-01, 1.7539e-01, 6.7176e-01, 9.4396e-01, 2.3013e-01],
         [6.4611e-01, 6.1072e-01, 4.1485e-01, 7.7090e-01, 3.2929e-01,
          9.4470e-01, 7.3972e-01, 5.6841e-01, 6.5713e-01, 1.5118e-01],
         [8.5516e-01, 3.7020e-01, 8.7493e-01, 1.6556e-01, 6.2541e-01,
          6.6932e-01, 7.6624e-01, 6.6288e-01, 2.3445e-01, 5.3793e-01],
         [6.1

In [10]:
random_tensor.ndim

3

In [11]:
 #Random Tensor With shape of an image
 random_image = torch.rand(size = (224,224,3 )) #height, width Colour Channel

In [12]:
random_image, random_image.shape

(tensor([[[0.4646, 0.8677, 0.2717],
          [0.5831, 0.0759, 0.7471],
          [0.8629, 0.1277, 0.2704],
          ...,
          [0.5881, 0.0924, 0.8154],
          [0.6079, 0.3201, 0.0515],
          [0.4224, 0.8325, 0.7040]],
 
         [[0.3192, 0.3686, 0.9285],
          [0.3228, 0.9981, 0.4853],
          [0.3374, 0.2108, 0.3309],
          ...,
          [0.8200, 0.7283, 0.5502],
          [0.5987, 0.7634, 0.9719],
          [0.3076, 0.8692, 0.2920]],
 
         [[0.8595, 0.5156, 0.8343],
          [0.4451, 0.3445, 0.0595],
          [0.1837, 0.3859, 0.2879],
          ...,
          [0.3254, 0.0345, 0.0972],
          [0.4713, 0.3244, 0.8197],
          [0.9250, 0.9918, 0.1693]],
 
         ...,
 
         [[0.3193, 0.8771, 0.6544],
          [0.2326, 0.0223, 0.0186],
          [0.7467, 0.5662, 0.8397],
          ...,
          [0.3208, 0.0408, 0.5248],
          [0.7468, 0.1213, 0.8599],
          [0.3507, 0.0167, 0.0618]],
 
         [[0.1641, 0.1838, 0.2909],
          [0

### zeros and Ones

In [13]:
#Tensor of all zeros
#zeros are usually used for masking

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
#Tensor of all Ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
#data type of tensors
ones.dtype,zero.dtype,random_image.dtype

(torch.float32, torch.float32, torch.float32)

# Creating Range of Tensors and tensors-like

In [16]:
range_tensor  = torch.arange(start=0, end = 1000, step = 77)

In [17]:
#creating tensors alike
alike_tensor = torch.zeros_like(input=range_tensor)


In [18]:
alike_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

#Tensor Datatypes is one of the 3 big erros one can run into with pytorch and deep learning

1. Tensors not right datatype (Some Ops may not work)
2. Tensors not right Shape
3. Tensors not on the right device



In [19]:
#Tensor Datatypes
#Default Datatype for tensor is float32

float_32_tensor  = torch.tensor([3.0,4.0,5.0],dtype = None,
                                device = 'cpu', #what device the tensor is on
                                requires_grad = False)
float_32_tensor.dtype

torch.float32

In [20]:
#Changing the datatype of tha tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [21]:
#Getting Shape, Data Type and Device of a Tensor

float_16_tensor.dtype,float_16_tensor.shape,float_16_tensor.device

(torch.float16, torch.Size([3]), device(type='cpu'))

In [22]:
#Creating a random tensor with a datatype

rand = torch.rand(size = (1,3), dtype = torch.float16)
rand

tensor([[0.5537, 0.8071, 0.5991]], dtype=torch.float16)

In [23]:
#Manipulating Tensors


tensor_ops = torch.rand(1,3)
tensor_ops

tensor([[0.3069, 0.6005, 0.2665]])

In [24]:
tensor_ops + 100

tensor([[100.3069, 100.6005, 100.2665]])

In [25]:
tensor_ops * 100

tensor([[30.6902, 60.0497, 26.6483]])

In [26]:
tensor_ops - 10

tensor([[-9.6931, -9.3995, -9.7335]])

## Two type of multiplication


###Element Wise
######(done above)

###Matrix multiplication ( dot p)
#### Two rules must be following
####1. Inner Dimension must match
####2. Resulting Matrix Will be in outer Dimention

In [27]:
#torch.mm(tensor_ops,tensor_ops)
#Error as inner dimensions donot match


In [28]:
tensor2 = tensor_ops.T
#now with transpose we could now multiply

In [29]:
torch.mm(tensor_ops,tensor2)

tensor([[0.5258]])

##Tensor Aggregation (Finding min,max, mean, sum)

In [30]:
tensor_agg = torch.arange(1,100,10)

In [31]:
tensor_agg.min()

tensor(1)

In [32]:
tensor_agg.max()

tensor(91)

In [34]:
#tensor_agg.mean()
#Error because tensor_agg have datatype
# Now finding the right Datatype is crucial here
# as we know tensor_agg have datatype long but mean function could be in float the datatypes are not matching hence we have to convert it to float
torch.mean(tensor_agg.type(torch.float32))

tensor(46.)