<a href="https://colab.research.google.com/github/sardarabdulsammad/DeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
print(torch.__version__)

2.4.0+cu121


## tensors Introduction

### Creating Tensors

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
matrix.shape

torch.Size([2, 2])

##Random Tensors

Start with Random Number -> look at data -> update random numbers -> look at data -> update random numbers

In [15]:
#create random tensor

random_tensor = torch.rand(10,10,10)

In [16]:
random_tensor

tensor([[[7.7846e-01, 1.6999e-01, 5.2894e-01, 4.0149e-01, 2.9946e-01,
          8.2683e-01, 2.7340e-01, 6.2236e-01, 1.1001e-01, 7.0026e-01],
         [1.7470e-01, 6.5900e-01, 8.9255e-01, 9.4868e-01, 7.3027e-02,
          5.0157e-01, 6.1967e-02, 4.1554e-02, 4.3822e-01, 6.4812e-01],
         [1.3112e-01, 1.9512e-01, 8.4258e-01, 3.3438e-01, 6.5271e-01,
          7.8223e-02, 2.7010e-01, 4.7635e-01, 7.5099e-01, 8.5485e-01],
         [4.8447e-01, 6.5013e-01, 9.1952e-01, 5.0731e-01, 9.4001e-01,
          2.3401e-01, 1.5095e-01, 5.7331e-01, 3.2740e-01, 7.2060e-01],
         [3.5518e-01, 3.7910e-01, 3.4971e-01, 5.9123e-01, 1.3085e-01,
          9.1154e-01, 4.4075e-02, 3.3559e-01, 1.6078e-01, 4.5799e-01],
         [7.1367e-01, 1.2823e-01, 8.1269e-01, 2.1994e-02, 2.9510e-01,
          7.8390e-01, 6.6579e-01, 3.0905e-02, 3.7544e-01, 3.7513e-01],
         [3.8434e-01, 7.3851e-02, 6.8393e-01, 2.8033e-01, 5.7257e-01,
          7.2473e-01, 4.1713e-01, 9.3520e-01, 9.2864e-02, 9.0863e-01],
         [3.5

In [17]:
random_tensor.ndim

3

In [20]:
 #Random Tensor With shape of an image
 random_image = torch.rand(size = (224,224,3 )) #height, width Colour Channel

In [23]:
random_image, random_image.shape

(tensor([[[0.8082, 0.8576, 0.4921],
          [0.0760, 0.0010, 0.7132],
          [0.5172, 0.3774, 0.5529],
          ...,
          [0.9328, 0.4342, 0.5865],
          [0.1399, 0.3451, 0.1483],
          [0.2035, 0.0042, 0.0483]],
 
         [[0.4161, 0.4637, 0.6974],
          [0.3351, 0.0340, 0.1484],
          [0.5654, 0.0197, 0.6019],
          ...,
          [0.4093, 0.5151, 0.6835],
          [0.8743, 0.4178, 0.9285],
          [0.9857, 0.9881, 0.3689]],
 
         [[0.0784, 0.9856, 0.9468],
          [0.1219, 0.2454, 0.9186],
          [0.1169, 0.8663, 0.2770],
          ...,
          [0.4762, 0.9391, 0.2637],
          [0.4723, 0.6364, 0.2503],
          [0.5378, 0.7986, 0.6919]],
 
         ...,
 
         [[0.4704, 0.1853, 0.8645],
          [0.9206, 0.0566, 0.3150],
          [0.0504, 0.4590, 0.1577],
          ...,
          [0.3003, 0.2371, 0.3312],
          [0.4706, 0.8885, 0.7683],
          [0.5303, 0.8096, 0.1589]],
 
         [[0.3200, 0.3146, 0.8719],
          [0

### zeros and Ones

In [26]:
#Tensor of all zeros
#zeros are usually used for masking

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#Tensor of all Ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
#data type of tensors
ones.dtype,zero.dtype,random_image.dtype

(torch.float32, torch.float32, torch.float32)

# Creating Range of Tensors and tensors-like

In [36]:
range_tensor  = torch.arange(start=0, end = 1000, step = 77)

In [37]:
#creating tensors alike
alike_tensor = torch.zeros_like(input=range_tensor)


In [38]:
alike_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

#Tensor Datatypes is one of the 3 big erros one can run into with pytorch and deep learning

1. Tensors not right datatype (Some Ops may not work)
2. Tensors not right Shape
3. Tensors not on the right device



In [58]:
#Tensor Datatypes
#Default Datatype for tensor is float32

float_32_tensor  = torch.tensor([3.0,4.0,5.0],dtype = None,
                                device = 'cpu', #what device the tensor is on
                                requires_grad = False)
float_32_tensor.dtype

torch.float32

In [66]:
#Changing the datatype of tha tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [69]:
#Getting Shape, Data Type and Device of a Tensor

float_16_tensor.dtype,float_16_tensor.shape,float_16_tensor.device

(torch.float16, torch.Size([3]), device(type='cpu'))

In [71]:
#Creating a random tensor with a datatype

rand = torch.rand(size = (3,5), dtype = torch.float16)
rand

tensor([[0.4160, 0.2090, 0.3760, 0.1685, 0.9302],
        [0.8257, 0.8452, 0.4092, 0.8301, 0.0562],
        [0.5771, 0.9688, 0.6602, 0.7461, 0.8618]], dtype=torch.float16)

In [ ]:
#Manipulating Tensors

