<a href="https://colab.research.google.com/github/sardarabdulsammad/DeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
print(torch.__version__)

2.4.0+cu121


## tensors Introduction

### Creating Tensors

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape

torch.Size([2, 2])

##Random Tensors

Start with Random Number -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
#create random tensor

random_tensor = torch.rand(10,10,10)

In [ ]:
random_tensor

tensor([[[0.6556, 0.8341, 0.1900, 0.7143, 0.2855, 0.1609, 0.9972, 0.9015,
          0.1169, 0.8689],
         [0.8420, 0.7082, 0.4817, 0.6837, 0.9097, 0.0571, 0.4566, 0.7495,
          0.0201, 0.1078],
         [0.6886, 0.6230, 0.3849, 0.2203, 0.3997, 0.9673, 0.2918, 0.8235,
          0.5666, 0.8713],
         [0.4144, 0.0362, 0.7838, 0.8441, 0.8429, 0.4443, 0.5086, 0.4520,
          0.4305, 0.9091],
         [0.2300, 0.3854, 0.0090, 0.5315, 0.4700, 0.8827, 0.9393, 0.7267,
          0.2130, 0.9844],
         [0.9584, 0.3328, 0.0255, 0.9354, 0.9845, 0.0305, 0.3754, 0.8122,
          0.8802, 0.5761],
         [0.4186, 0.0937, 0.8509, 0.9065, 0.9532, 0.2720, 0.0317, 0.5099,
          0.5437, 0.2698],
         [0.3454, 0.9377, 0.6801, 0.9337, 0.4672, 0.5047, 0.0877, 0.0223,
          0.0979, 0.0526],
         [0.8298, 0.9463, 0.0509, 0.7409, 0.6138, 0.8132, 0.0442, 0.8102,
          0.3355, 0.5564],
         [0.3100, 0.4792, 0.5030, 0.7838, 0.6836, 0.8045, 0.5631, 0.7563,
          0.4958,

In [ ]:
random_tensor.ndim

3

In [ ]:
 #Random Tensor With shape of an image
 random_image = torch.rand(size = (224,224,3 )) #height, width Colour Channel

In [ ]:
random_image, random_image.shape

(tensor([[[0.9813, 0.3143, 0.6326],
          [0.1661, 0.5788, 0.1751],
          [0.3234, 0.9095, 0.2184],
          ...,
          [0.2495, 0.9257, 0.3445],
          [0.6480, 0.0211, 0.7705],
          [0.4762, 0.0825, 0.0881]],
 
         [[0.7285, 0.2052, 0.1299],
          [0.0909, 0.0954, 0.9223],
          [0.2279, 0.3581, 0.4609],
          ...,
          [0.5817, 0.2672, 0.8893],
          [0.6872, 0.0581, 0.4127],
          [0.2901, 0.2855, 0.6749]],
 
         [[0.9771, 0.0984, 0.2045],
          [0.6183, 0.6631, 0.3555],
          [0.5170, 0.5541, 0.8990],
          ...,
          [0.8001, 0.8244, 0.7063],
          [0.4884, 0.7288, 0.3348],
          [0.1366, 0.5445, 0.4284]],
 
         ...,
 
         [[0.6315, 0.8438, 0.5296],
          [0.4777, 0.0649, 0.8083],
          [0.3373, 0.4109, 0.7178],
          ...,
          [0.7687, 0.6929, 0.0410],
          [0.3266, 0.1388, 0.4458],
          [0.4721, 0.5912, 0.4016]],
 
         [[0.3063, 0.4120, 0.3682],
          [0

### zeros and Ones

In [ ]:
#Tensor of all zeros
#zeros are usually used for masking

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Tensor of all Ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#data type of tensors
ones.dtype,zero.dtype,random_image.dtype

(torch.float32, torch.float32, torch.float32)

# Creating Range of Tensors and tensors-like

In [ ]:
range_tensor  = torch.arange(start=0, end = 1000, step = 77)

In [ ]:
#creating tensors alike
alike_tensor = torch.zeros_like(input=range_tensor)


In [ ]:
alike_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

#Tensor Datatypes is one of the 3 big erros one can run into with pytorch and deep learning

1. Tensors not right datatype (Some Ops may not work)
2. Tensors not right Shape
3. Tensors not on the right device



In [ ]:
#Tensor Datatypes
#Default Datatype for tensor is float32

float_32_tensor  = torch.tensor([3.0,4.0,5.0],dtype = None,
                                device = 'cpu', #what device the tensor is on
                                requires_grad = False)
float_32_tensor.dtype

torch.float32

In [ ]:
#Changing the datatype of tha tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
#Getting Shape, Data Type and Device of a Tensor

float_16_tensor.dtype,float_16_tensor.shape,float_16_tensor.device

(torch.float16, torch.Size([3]), device(type='cpu'))

In [ ]:
#Creating a random tensor with a datatype

rand = torch.rand(size = (1,3), dtype = torch.float16)
rand

tensor([[0.7676, 0.2510, 0.9717]], dtype=torch.float16)

In [ ]:
#Manipulating Tensors


tensor_ops = torch.rand(1,3)
tensor_ops

tensor([[0.3705, 0.5383, 0.5833]])

In [ ]:
tensor_ops + 100

tensor([[100.3705, 100.5383, 100.5833]])

In [ ]:
tensor_ops * 100

tensor([[37.0496, 53.8318, 58.3329]])

In [ ]:
tensor_ops - 10

tensor([[-9.6295, -9.4617, -9.4167]])

## Two type of multiplication


###Element Wise
######(done above)

###Matrix multiplication ( dot p)
#### Two rules must be following
####1. Inner Dimension must match
####2. Resulting Matrix Will be in outer Dimention

In [ ]:
#torch.mm(tensor_ops,tensor_ops)
#Error as inner dimensions donot match


In [ ]:
tensor2 = tensor_ops.T
#now with transpose we could now multiply

In [ ]:
torch.mm(tensor_ops,tensor2)

tensor([[0.7673]])

##Tensor Aggregation (Finding min,max, mean, sum)

In [ ]:
tensor_agg = torch.arange(1,100,10)

In [ ]:
tensor_agg.min()

tensor(1)

In [ ]:
tensor_agg.max()

tensor(91)

In [ ]:
#tensor_agg.mean()
#Error because tensor_agg have datatype
# Now finding the right Datatype is crucial here
# as we know tensor_agg have datatype long but mean function could be in float the datatypes are not matching hence we have to convert it to float
torch.mean(tensor_agg.type(torch.float32))

tensor(46.)

## Finding the positional min and max
## Index of  min and max

In [ ]:
tensor_agg.argmin()

tensor(0)

In [ ]:
tensor_agg.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing and Unsqueezing

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original torch.tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all '1' dimensions from a tensor
* Unsqueeze - Add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [5]:
#Reshaping

import torch
x= torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x.shape

torch.Size([9])

In [7]:
x.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [8]:
z=x.view(1,9) #same as reshape but new shape will have same reference as old one.
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
#stacking

x_stacked = torch.stack([x,x,x,x])

In [10]:
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [12]:
#squeeze removes all single dimensions
x.size()

torch.Size([9])

In [13]:
#since x has the single dimension of size 9 it has no 1 dimension so no effect will be of squeeze function
x_new = torch.squeeze(x)
x_new

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x_new2 = x.unsqueeze()

TypeError: unsqueeze() missing 1 required positional arguments: "dim"

In [ ]:
#permutation
img_tens  = torch.rand(size = (224,244,3))
i

In [ ]:
x.size()

In [ ]:
x.permute(2,0,1).size()

##Permutation

####permutation is a view that means it shares the same memory as the original tensor

In [16]:

import torch
image_tensor = torch.rand(size = (224,224,3))

In [18]:
permuted_ = image_tensor.permute(2,0,1)
permuted_.size()

torch.Size([3, 224, 224])

##Indexing

####Selecting Data from indexing

#similar to that of numpy

In [25]:
image_tensor[0,0,0] , permuted_[0,0,0]

(tensor(0.0800), tensor(0.0800))

##numpy to pytorch
#### torch.from_numpy(ndarray)
##pytorch to numpy
#### torch.tensor.numpy()


###numpy default datatype is float64 and torch datatype is float 32


In [29]:
import numpy as np
array  = np.arange(1.0,8.0)
tensor_ =torch.from_numpy(array)

##Reproducibility
####Trying to take out random out of random
'Start with random numbers - > performs tensor operations -> update random numbers to make them better representation of the data -> again '


#### but Randomization is also a problem, and to reduce it in neural network and pytorch their comes a concept of **random seed**

In torch it is called **manual seed**

In [36]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_seed_tensor1 = torch.rand(size=(3,4))

#To make sure that tensor is random with the seed you need to put this manual_seed line above
torch.manual_seed(RANDOM_SEED)
random_seed_tensor2 = torch.rand(size=(3,4))
print(random_seed_tensor1)
print(random_seed_tensor2)
print(random_seed_tensor1 == random_seed_tensor2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and pytorch objects on GPUs



### 1. Getting a GPU

1 - Use google collab pro
2 - Use your own
3 - Use cloud computing - GCP AWS or AZURE
for 2 and 3 takes little bit of setup > for that you can go to pytorch.org

In [42]:
#2. Some device agnostic code below
import torch
torch.cuda.is_available()

False

In [43]:
device = "cude" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [44]:
torch.cuda.device_count()

0

## 3. putting tensors and models on GPU

In [46]:
tensor = torch.tensor([1,2,3])
print(tensor , device)

tensor([1, 2, 3]) cpu


In [48]:
#Move tensor to GPU if avilable
#you can make a device of GPU
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3])

In [52]:
#4. Moving Tensors back to CPU
#also when tensors in GPU you cannot change tensor to Numpy
tensor_back_on_cpu = tensor_to_gpu.cpu()
tensor_back_on_cpu.numpy()




array([1, 2, 3])